name: student_manegment_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_core: ^3.1.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.2
  firebase_auth: ^5.1.2

  pdfx: ^2.6.0
  internet_file: ^1.2.0

  go_router: ^14.2.1

  provider: ^6.1.2

  lottie: ^3.0.0

  path_provider: ^2.1.4

  toastification: ^2.1.0

  permission_handler: ^11.3.1

  file_picker: ^8.0.5

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: dmsans
      fonts:
        - asset: assets/fonts/DMSans.ttf
    - family: montserrat
      fonts:
        - asset: assets\fonts\Montserrat.ttf
